version: "3.0"
services:
  vote:
    container_name: vote
    build:
      context: vote
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
    links:
      - "redis"
    depends_on:
      - redis
    volumes:
      - ./vote:/app
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"